---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops-smoke-test
  labels:
    app.kubernetes.io/managed-by: flux
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
