---
- name: Reapply NetworkManager connection
  ansible.builtin.command:
    argv:
      - nmcli
      - device
      - reapply
      - "{{ ansible_facts['default_ipv4']['interface'] }}"
  changed_when: true
