---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-backup
resources:
  - ../talos
  - job.yaml
replacements:
  - source:
      group: batch
      version: v1
      kind: CronJob
      name: talos-backup
      fieldPath: spec.jobTemplate.spec.template
    targets:
      - select:
          group: batch
          version: v1
          kind: Job
          name: talos-backup-poc-v1
        fieldPaths:
          - spec.template
