---
instance:
  distribution:
    version: "2.9.6"
    registry: ghcr.io/fluxcd
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:v0.61.0
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    domain: cluster.local
    networkPolicy: true
    multitenant: false
  sync:
    interval: 1m
    kind: GitRepository
    url: https://github.com/nunoferna/talos-homelab.git
    ref: refs/heads/main
    path: clusters/homelab
    name: flux-system

healthcheck:
  enabled: true
  timeout: 10m
